Remove player's polls on disconnect
neu-cs4530/spring-23-team-203 pull request #51
Opened 2023-04-06 15:17 UTC by dfarooq610

Now, we remove that player's polls once they disconnect. The polls window only shows the polls created by players in the town. Included a test on town.test.ts to confirm that even if their polls are gone their votes remain.

in retrospect, maybe we should never delete polls but instead, have an archived polls list or something. but that isn't in the books and I can include that in the "future work" on the poster/report.

2023-04-06 22:32 UTC, DavtyanA requested changes
Looks really good, however, I would suggest making your repo private, because right now I can see it, and I'm from team 212 (I just saw it when I clicked on neu-cs4530 thing on github). hehehe https://youtu.be/HPd2hiYreyc

2023-04-06 22:41 UTC, dfarooq610 commented
@DavtyanA do you get notifs when we do stuff on the repo? or are you just snooping?

the website indicated you could make the repo public for demos, so we opted for that

also, https://isotropic.org/papers/chicken.pdf

2023-04-07 01:52 UTC, vandevenj approved these changes
LGTM (Laggy Games Trample Hearts)

2023-04-07 02:24 UTC, DavtyanA commented
@dfarooq610 nope, I don't get any notifs, I just thought you guys accidentally made your repo public, didn't know it was an option for everyone. BTW your poll demo was really cool, looking forward to the full one!

2023-04-07 21:56 UTC, merged